# Start from the official Nginx base image
FROM nginx:latest

# Copy custom Nginx configuration file to the Nginx configuration directory
COPY nginx.conf /etc/nginx/nginx.conf

# Copy HTML content to the default Nginx HTML directory
COPY html/ /usr/share/nginx/html/

# Expose port 80 to access the web server
EXPOSE 80

# Start the Nginx server
CMD ["nginx", "-g", "daemon off;"]
#3. Nginx Configuration File (nginx.conf)